#### 가상환경 구축하기
 - 가상환경 이름 : dataproc
 - conda deactivate // 가상환경 비활성화
 - conda activate dataproc // 가상환경 활성화
 - conda list // list 확인
 - conda install ipkernel // ipkernel 설치

 - 엑셀 바로 읽기 : conda install xlrd, conda install openyxl

### 01 서울시 구별 CCTV 현황 분석

[학습목표]

- 서울시 각 구별 CCTV 수를 파악하고, 인구대비 CCTV 비율을 파악해서 순위 비교
- 인구대비 CCTV의 평균치를 확인하고, CCTV가 과하게 부족한 구를 확인
- pandas 사용법과 시각화(matplotlib) 사용법을 배운다

# commit 확인

#### 판다스 라이브러리 

- 판다스 : python의 데이터 분석 및 조작을 위한 라이브러리로 
- 표(데이터프레임)형식 데이터를 다루는 강력한 기능 제공
- 엑셀, SQL, CSV 등의 데이터를 불러와 정리, 분석, 변환, 저장하는 기능
- 데이터 분석에 필수적인 라이브러리이다. 

1. Pandas 핵심 구조
- Pandas에는 Series와 DataFrame 두 가지 주요 데이터 구조가 있다

1.1 Series (1차원 데이터 처리시 사용)
- 단일 컬럼 형태의 데이터 구조를 가지고 있다 (시리즈로 컬럼단위 처리)
- 리스트(list)나 배열(array)과 유사하고 인덱스를 사용한다(인덱싱, 슬라이싱 가능)

1.2 DataFrame (2차원 데이터 처리시 사용)
- 엑셀의 표와 같은 행(row)-열(column) 구조
- 여러개의 Series(컬럼)으로 구성된 것이다


1. Series attribute (변수)
- index : 인덱스 저장 (array)
- values : 값 저장 (array)
- dtype : 데이터 타입 저장
- name : series object 이름 => 데이터프레임으로 가면 컬럼명으로 사용된다.

2. Series 데이터 타입
- index, value 다 array 형식으로 저장
- array 형식 : 넘파이 저장
    - 동일 데이터 타입만 저장 가능
    - 데이터 타입 세분화 된다
    - 정수, 실수, 문자열 등등 다 별도의 데이터 타입 있다.

In [5]:
# 예제 1 : Series 생성

import pandas as pd # 별칭
# data에 들어갈 수 있는 것 : 리스트, 딕셔너리, 배열 가능
data = [1,2,3,4]
series = pd.Series(data)
print(series)
print(series.index)
print(series.values)

series.name = '컬럼명'
print(type(series.values))

0    1
1    2
2    3
3    4
dtype: int64
RangeIndex(start=0, stop=4, step=1)
[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
# 0123 = index
# 1234 = values
# RangeIndex(start=0, stop=4, step=1) // 0이상 4미만 1씩 증가 = 0123
# <class 'numpy.ndarray'> = array // 판다스 내부 엔진이 numpy 그래서 고속처리가 가능함

In [13]:
# 2. 데이터프레임 생성
# 딕셔너리로 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Seoul', 'Busan', 'Incheon']
}
# print(data)
df = pd.DataFrame(data)
print(df)

      Name  Age     City
0    Alice   25    Seoul
1      Bob   30    Busan
2  Charlie   35  Incheon


In [14]:
# key = Name
# value = Alice, Bob, Charlie
# 이게 한개의 series
# 즉, 총 3개의 series가 있다.

In [15]:
# 특정 컬럼 선택
# 컬럼들 확인
print(df.columns)

print(df['Name'])
print(df['Age'])

Index(['Name', 'Age', 'City'], dtype='object')
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
0    25
1    30
2    35
Name: Age, dtype: int64


In [16]:
# DataFrame 주요 속성(attribute)
# 1. colums : 컬럼들을 관리
# 2. index : 인덱스 관리
# 3. dtype : 컬럼별 데이터 타입 관리
# 4. shape : 데이터 구좌 (행X열)

print(df.columns)
print(df.index)
print(df.values)
print(type(df.values)) # array => numpy 전용 데이터 저장 방법
print(df.shape) # (3,3) tuple

Index(['Name', 'Age', 'City'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
[['Alice' 25 'Seoul']
 ['Bob' 30 'Busan']
 ['Charlie' 35 'Incheon']]
<class 'numpy.ndarray'>
(3, 3)


In [17]:
# object = 문자열, string
# RangeIndex(start=0, stop=3, step=1) // 0이상 3미만
# [['Alice' 25 'Seoul']
# ['Bob' 30 'Busan']
# ['Charlie' 35 'Incheon']]
# <class 'numpy.ndarray'>       // 리스트가 아니라 array, 판다스 안에 들어있는 값은 다 array

---
#### CCTV 현황 데이터 읽기
---

In [18]:
# CCTV 현황 데이터 읽기
# 파일 : data_collection/data/01. CCTV_in_Seoul.csv
# csv 읽기 함수 : pd.readcsv() => return DataFrame object
import pandas as pd
import numpy as np

CCTV_Seoul = pd.read_csv(
    './data/01. CCTV_in_Seoul.csv', # 파일과 파일의 경로 지정
    encoding='utf-8'                # 한글을 유니코드를 사용해서 읽기
)
# print(CCTV_Seoul) # 전체 데이터 확인
# print(CCTV_Seoul.head()) # 상위 5개
# print(CCTV_Seoul.tail()) # 하위 5개
CCTV_Seoul.head(10) # 상위 10개 행 데이터가 추출 => return = DataFrame 

기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613
5  광진구   707        573     78     53    174
6  구로구  1561       1142    173    246    323
7  금천구  1015        674     51    269    354
8  노원구  1265        542     57    451    516
9  도봉구   485        238    159     42    386

In [19]:
# CCTV_Seoul DataFrame 구조 확인

# 1. 행정보 추출
# CCTV_Seoul.index : RangeIndex(start=0, stop=25, step=1) : 정수인덱스
# 2. 컬럼들 추출
print(CCTV_Seoul.columns)
# 2.1 특정 컬럼 추출
print(CCTV_Seoul.columns[0])
print(CCTV_Seoul.columns[-1])
# 3. 구조 추출
print(CCTV_Seoul.shape) # (25,6) : 25행, 6개 컬럼 // 튜플이다. = 인덱스가 있다.
                        # 밑에처럼 이렇게 개수확인도 가능하다.
print(CCTV_Seoul.shape[0]) # 데이터 개수 확인
print(CCTV_Seoul.shape[1]) # 데이터 개수 확인

Index(['기관명', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')
기관명
2016년
(25, 6)
25
6


In [20]:
# 수치 데이터의 기본 통계량
# CCTV_Seoul.head(2) // 이렇게 확인을 하고 
# CCTV_Seoul['기관명'].dtype # 컬럼 추출 => series object => dtype
# return dtype('O') : 문자열
CCTV_Seoul.describe()['소계'] # return = DataFrame

count      25.000000
mean     1179.080000
std       556.728983
min       485.000000
25%       748.000000
50%      1015.000000
75%      1496.000000
max      2780.000000
Name: 소계, dtype: float64

In [21]:
# std = 분산 = 평균에서 어느정도 떨어져 있는 정도 = 퍼져 있는 정도 // 분산이 너무 크면 신경망 모델이 안좋다.
# min~max = 4분위

In [22]:
# 데이터 전체 구조 확인 (DataFrame) 메소드 : info()
CCTV_Seoul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   기관명        25 non-null     object
 1   소계         25 non-null     int64 
 2   2013년도 이전  25 non-null     int64 
 3   2014년      25 non-null     int64 
 4   2015년      25 non-null     int64 
 5   2016년      25 non-null     int64 
dtypes: int64(5), object(1)
memory usage: 1.3+ KB


In [43]:
# 컬럼명 수정 : 기관명 => 구별
# 메소드 : rename()
gu = {
    CCTV_Seoul.columns[0]:'구별'
}
CCTV_Seoul.rename(
    columns=gu
)

구별    소계  2013년도 이전  2014년  2015년  2016년
0    강남구  2780       1292    430    584    932
1    강동구   773        379     99    155    377
2    강북구   748        369    120    138    204
3    강서구   884        388    258    184     81
4    관악구  1496        846    260    390    613
5    광진구   707        573     78     53    174
6    구로구  1561       1142    173    246    323
7    금천구  1015        674     51    269    354
8    노원구  1265        542     57    451    516
9    도봉구   485        238    159     42    386
10  동대문구  1294       1070     23    198    579
11   동작구  1091        544    341    103    314
12   마포구   574        314    118    169    379
13  서대문구   962        844     50     68    292
14   서초구  1930       1406    157    336    398
15   성동구  1062        730     91    241    265
16   성북구  1464       1009     78    360    204
17   송파구   618        529     21     68    463
18   양천구  2034       1843    142     30    467
19  영등포구   904        495    214    195    373
20   용산구  1624       1368    218    112    398
21   은평구  1873       1138    224    278    468
22   종로구  1002        464    314    211    630
23    중구   671        413    190     72    348
24   중랑구   660        509    121    177    109

In [23]:
CCTV_Seoul.head()
# 원문에 반영안됨

기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [ ]:
# 컬럼명 변경 : 원본 반영 안되었다
# 원본에 반영하는 방법 2가지
# 1. 다시 대입 : 기관명 => 구별
CCTV_Seoul = CCTV_Seoul.rename(columns=gu)
CCTV_Seoul.columns

# 2. inplace=True : 구별 => 기관명
gu={
    CCTV_Seoul.columns[0] : '기관명'
}
CCTV_Seoul.rename(columns=gu, inplace=True)
CCTV_Seoul.columns

# 3. 기관명 => 구별 변경
gu={
    CCTV_Seoul.columns[0] : '구별'
}
CCTV_Seoul.rename(columns=gu, inplace=True)
CCTV_Seoul.columns

Index(['구별', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')

---
#### 인구현황 데이터 처리
---

In [ ]:
# 엑셀 파일 읽기
# xls => xlrd module, xlsx => openyxl module install
POP_seoul = pd.read_excel(
    './data/01. population_in_Seoul.xls' # 파일의 경로와 파일명
    , header=2 # 0,1,2니까 3번째
    # 여기까지 리턴타입 데이터프레임
    , usecols='B,D,G,J,N' # 엑셀파일에서 가져올 컬럼들
)
POP_seoul.head()

자치구           계        계.1       계.2   65세이상고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [ ]:
POP_seoul.columns
# 컬럼명 변경
# ['자치구', '계', '계.1', '계.2', '65세이상고령자'] - 원래 컬럼명
# ['구별', '인구수', '한국인', '외국인', '고령자']
columns = {
    POP_seoul.columns[0] : '구별'
    , POP_seoul.columns[1] : '인구수'
    , POP_seoul.columns[2] : '한국인'
    , POP_seoul.columns[3] : '외국인'
    , POP_seoul.columns[4] : '고령자'
}

POP_seoul.rename(
    columns=columns
    , inplace=True
)

# 변경 확인
POP_seoul.columns

Index(['구별', '인구수', '한국인', '외국인', '고령자'], dtype='object')

In [66]:
POP_seoul.tail(3)

구별       인구수       한국인     외국인      고령자
24  송파구  667483.0  660584.0  6899.0  72506.0
25  강동구  453233.0  449019.0  4214.0  54622.0
26  NaN       NaN       NaN     NaN      NaN

--- 
### 판다스 기본
---

---
#### Series 생성 방식 1
---

In [24]:
# Series 생성 방식 1
data = [10,20,30,40,50] # list
index = ['a', 'b', 'c', 'd', 'e'] # 인덱스에 날짜와 시간이 들어갈 수 있다.
series = pd.Series(data=data, index=index)
print(series)
print(series['a'])

a    10
b    20
c    30
d    40
e    50
dtype: int64
10


---
#### Series 생성 방식 2
---

In [26]:
# Series 생성 방식 2
data_index = {
    'a' : 10
    ,'b' :  20
    ,'c' :  30
    ,'d' :  40
    ,'e' :  50
}

series = pd.Series(data_index)
print(series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [27]:
# series로 만들면 키가 인덱스로 들어간다.
# vs dataframe은 키가 컬럼으로 들어간다.

---
#### Series 생성 방식 3
---

In [ ]:
# Series 3
# 스칼라값(단일값)과 인덱스 리스트로 시리즈 생성
data = 5 # 스칼라값
index = ['a','b','c']
series = pd.Series(data=data, index=index)
series

a    5
b    5
c    5
dtype: int64

---
#### Series 생성 방식 4
---

In [67]:
# Series 4
series = pd.Series(
    data=[1,2,3]
    , index=['a','b','c']
    , name = 'sample_series'
    , dtype = 'int8'
)

series

a    1
b    2
c    3
Name: sample_series, dtype: int8

In [ ]:
# PDF in[10] : nan(not a number) : 결측치(없는 데이터), 무한대 의미가 있다.
import numpy as np

s = pd.Series(data=[1,3,5,np.nan,6,8]) # data argument가 첫번째다
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

---
#### 판다스에서 날짜 데이터 생성
---

In [29]:
# 판다스에서 날짜 시간 데이터 생성 : date_range()
import pandas as pd

dates = pd.date_range(
    '20250227' # 시작일
    , periods=6
    , freq='D' # 날짜를 만들라는 뜻 // 일자단위
)
dates

DatetimeIndex(['2025-02-27', '2025-02-28', '2025-03-01', '2025-03-02',
               '2025-03-03', '2025-03-04'],
              dtype='datetime64[ns]', freq='D')

In [30]:
print(np.arange(24))
print(np.arange(24).shape)
print(np.arange(24).reshape(6,4))
print(np.random.randn(6,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[-0.32353095  1.60319124 -0.29149649  0.13961185]
 [ 0.07261947 -0.22539517  2.18008847  1.63408715]
 [ 2.06835774  1.6791538   0.69665038 -0.15019435]
 [-0.81261638 -0.47189947  0.39755432  0.53157608]
 [ 1.16620623 -0.17752492 -1.59160101  0.09739761]
 [ 0.38921764  1.07863281  0.63130307  0.39722064]]


In [ ]:
# DF(데이터프레임) 생성
import numpy as np

df = pd.DataFrame(
    np.arange(24).reshape(6,4) # data에 들어가는 값
    , index=dates
    , columns=['A','B','C','D']
)
df # 데이터프레임 생성

A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23

In [81]:
print(df.index)
print(df.columns)
print(df.values)

DatetimeIndex(['2025-02-27', '2025-02-28', '2025-03-01', '2025-03-02',
               '2025-03-03', '2025-03-04'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# 2.28 금

In [84]:
# 데이터 구조, 정보 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2025-02-27 to 2025-03-04
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      int64
 1   B       6 non-null      int64
 2   C       6 non-null      int64
 3   D       6 non-null      int64
dtypes: int64(4)
memory usage: 240.0 bytes


In [ ]:
# 기본 통계
df.describe()
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]
#  [12 13 14 15]
#  [16 17 18 19]
#  [20 21 22 23]]
# 0 4 8 12 16 20 이런식으로 데이터를 봐야함

A          B          C          D
count   6.000000   6.000000   6.000000   6.000000
mean   10.000000  11.000000  12.000000  13.000000
std     7.483315   7.483315   7.483315   7.483315
min     0.000000   1.000000   2.000000   3.000000
25%     5.000000   6.000000   7.000000   8.000000
50%    10.000000  11.000000  12.000000  13.000000
75%    15.000000  16.000000  17.000000  18.000000
max    20.000000  21.000000  22.000000  23.000000

In [32]:
# 데이터 처리
# 1. 정렬 (오름차순(ascending), 내림차순)
# B 컬럼의 값으로 내림차순
# df.sort_values(by='컬럼명', ascending=정렬방식 지정(True, False)) # 값으로 정렬
df.sort_values(by='B', ascending=False) # 원본에 반영되지 않았다
# True = ascending , False = descending

A   B   C   D
2025-03-04  20  21  22  23
2025-03-03  16  17  18  19
2025-03-02  12  13  14  15
2025-03-01   8   9  10  11
2025-02-28   4   5   6   7
2025-02-27   0   1   2   3

In [ ]:
# 시리즈에서 인덱싱, 슬라이싱 : PDF in[22]
# df dataframe에서 시리즈 추출 : column 한개는 series다 // series들이 모여서 dataframe이 된다.
df['A']

2025-02-27     0
2025-02-28     4
2025-03-01     8
2025-03-02    12
2025-03-03    16
2025-03-04    20
Freq: D, Name: A, dtype: int64

In [ ]:
# in[23] : 데이터프레임에서 슬라이싱
# df[0:3]
# named index 사용 // 날짜여도 문자로 들어간다.
# df['20250227':'20250302'] 
df['20250227':'20250301']
# named index에서 주의 : 1. end-1 안된다.
# 슬라이싱 : return = DataFrame // series가 아니다.

A  B   C   D
2025-02-27  0  1   2   3
2025-02-28  4  5   6   7
2025-03-01  8  9  10  11

In [95]:
df

A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23

In [ ]:
# in[25]
# df.loc['20250227'] named index => 행단위 추출
df.iloc[0] # integer index => 행단위 추출

A    0
B    1
C    2
D    3
Name: 2025-02-27 00:00:00, dtype: int64

In [ ]:
# loc, iloc 데이터 추출 : loc[], iloc[]
# 1. loc[행,열]
# df.loc[start:end ,['A','C']]
# ['A','C']]의 구조 = A컬럼과 C컬럼만 추출하라는 뜻
df.loc[ : ,['A','C']]
# start, end가 없다? 전체를 가져오라는 뜻

A   C
2025-02-27   0   2
2025-02-28   4   6
2025-03-01   8  10
2025-03-02  12  14
2025-03-03  16  18
2025-03-04  20  22

In [33]:
# 날짜 인덱스로 접근
df.loc['20250228':'20250302'] 
# df.loc[ : ,['A','C'] 이런식으로 콤마가 없으면 행만 가져오라는 뜻

A   B   C   D
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15

In [ ]:
df.loc['20250228':'20250302',['A','D']] # 슬라이싱 : 여러개 추출

A   D
2025-02-28   4   7
2025-03-01   8  11
2025-03-02  12  15

In [ ]:
# 팬시 색인
# 대괄호 안에 대괄호
# 연속되지 않은 값을 뽑아내고 싶으면 무조건 팬시색인을 써야한다.
df.loc[['20250228','20250302'],['B','D']]

B   D
2025-02-28   5   7
2025-03-02  13  15

In [104]:
df

A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23

In [111]:
df.loc['20250228','A':'B']

A    4
B    5
Name: 2025-02-28 00:00:00, dtype: int64

In [114]:
print(df.loc['20250301','C'])
print(df.iloc[2,2])

10
10


In [115]:
df

A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23

In [ ]:
# 03-01 행추출 - 행단위로 접근
print(df.loc['20250301']) # 인덱싱
print(df.loc['20250301',:]) #슬라이싱

# C 컬럼 추출
# print(df['C']) # 컬럼단위 접근
# 즉, 대괄호는 컬럼 단위 접근
# print(df.loc[:,'C']) # 행을 먼저 접근, 컬럼 접근
# 즉, loc는 행 먼저 접근 후 컬럼 접근
print(df)

A     8
B     9
C    10
D    11
Name: 2025-03-01 00:00:00, dtype: int64
A     8
B     9
C    10
D    11
Name: 2025-03-01 00:00:00, dtype: int64
             A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23


In [ ]:
# IN[31] : integer index 사용한 슬라이싱
# integer index = end -1
df.iloc[3:5,0:2]

A   B
2025-03-02  12  13
2025-03-03  16  17

In [136]:
# # IN[32] integer index 사용한 팬시 색인 : 비연속적인 데이터를 여러개 추출
# print(df.iloc[[1,3,5][0,2]])
# print(df)

In [137]:
# IN[33] : integer index
df.iloc[1:3,:]

A  B   C   D
2025-02-28  4  5   6   7
2025-03-01  8  9  10  11

In [36]:
# IN[34]
print(df.iloc[:,1:3])
print(df[['B','C']])
# dataframe형식으로 나온다.
# 즉, loc, iloc는 행 접근이다.

             B   C
2025-02-27   1   2
2025-02-28   5   6
2025-03-01   9  10
2025-03-02  13  14
2025-03-03  17  18
2025-03-04  21  22
             B   C
2025-02-27   1   2
2025-02-28   5   6
2025-03-01   9  10
2025-03-02  13  14
2025-03-03  17  18
2025-03-04  21  22


In [37]:
# DataFrame에서 인덱싱(슬라이싱)
# 인덱싱, 슬라이싱, 팬시색인, 불린인덱싱
# 불린(조건) 인덱싱 : 조건에 맞는 데이터만 추출
print(df)
# print(df[조건]) : 조건에 맞는 행 추출
print(df[df['A'] < 5]) 
df['A'] < 5

             A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23
            A  B  C  D
2025-02-27  0  1  2  3
2025-02-28  4  5  6  7


2025-02-27     True
2025-02-28     True
2025-03-01    False
2025-03-02    False
2025-03-03    False
2025-03-04    False
Freq: D, Name: A, dtype: bool

In [155]:
# df2 = df # 복사가 아니다
df2 = df.copy()
id(df2) is id(df)

False

In [156]:
# IN[38] : 데이터프레임에서 컬럼 추가
df2['E'] = ['one','one','two','three','four','three']
df2

A   B   C   D      E
2025-02-27   0   1   2   3    one
2025-02-28   4   5   6   7    one
2025-03-01   8   9  10  11    two
2025-03-02  12  13  14  15  three
2025-03-03  16  17  18  19   four
2025-03-04  20  21  22  23  three

In [ ]:
# IN[39] : isin([여러개]) method : 불린인덱싱
# df2['E'] # series object
df2['E'].isin(['two'])
# series 안에 isin()이라는 메소드가 있음
# 특정값만 추출할 때 사용

2025-02-27    False
2025-02-28    False
2025-03-01     True
2025-03-02    False
2025-03-03    False
2025-03-04    False
Freq: D, Name: E, dtype: bool

In [ ]:
# IN[40]
df2[df2['E'].isin(['two'])]
# df[조건식] :True 행 추출

A  B   C   D    E
2025-03-01  8  9  10  11  two

#### list의 두가지 기능 = 여러개 저장, 묶는다

---
#### date_range function
---

- 용도 : 일정 기간 동안의 날짜 범위를 생성하는데 사용, 주로 시계열 데이터 처리에 유용
- date_range(start, end, periods, freq, tz)

In [165]:
dates = pd.date_range('20250228', periods=7)
print(dates)


DatetimeIndex(['2025-02-28', '2025-03-01', '2025-03-02', '2025-03-03',
               '2025-03-04', '2025-03-05', '2025-03-06'],
              dtype='datetime64[ns]', freq='D')


In [ ]:
series = pd.Series(
    data=[1,2,3,4,5,6,7]
    , index=dates
)
print(series)
# 슬라이싱 (연속된 데이터값 추출)
print(series['20250228':'20250302'])

2025-02-28    1
2025-03-01    2
2025-03-02    3
2025-03-03    4
2025-03-04    5
2025-03-05    6
2025-03-06    7
Freq: D, dtype: int64
2025-02-28    1
2025-03-01    2
2025-03-02    3
Freq: D, dtype: int64


In [ ]:
# 범위의 날짜로 생성 : 일단위 생성
date_range = pd.date_range(
    start = '20250228'
    , end = '20250618'
)
print(date_range)

DatetimeIndex(['2025-02-28', '2025-03-01', '2025-03-02', '2025-03-03',
               '2025-03-04', '2025-03-05', '2025-03-06', '2025-03-07',
               '2025-03-08', '2025-03-09',
               ...
               '2025-06-09', '2025-06-10', '2025-06-11', '2025-06-12',
               '2025-06-13', '2025-06-14', '2025-06-15', '2025-06-16',
               '2025-06-17', '2025-06-18'],
              dtype='datetime64[ns]', length=111, freq='D')


In [ ]:
# freq : 생성할 날짜 시간의 단위 지정
# 시간단위 생성
date_range = pd.date_range(
    start='20250228'
    , periods=10
    , freq='h'
)
print(date_range)
# 시간 단위로 쪼개지는 날짜 데이터를 생성할 수 있다.

DatetimeIndex(['2025-02-28 00:00:00', '2025-02-28 01:00:00',
               '2025-02-28 02:00:00', '2025-02-28 03:00:00',
               '2025-02-28 04:00:00', '2025-02-28 05:00:00',
               '2025-02-28 06:00:00', '2025-02-28 07:00:00',
               '2025-02-28 08:00:00', '2025-02-28 09:00:00'],
              dtype='datetime64[ns]', freq='h')


In [ ]:
# freq = value
# value
# D : 일단위, B : 주말을 제외한 평일, h : 시간단위, min : 분단위, s : 초단위, ms : 밀리초단위
# W : 주단위, ME : 월단위, QE : 분기단위, YE : 연단위

In [177]:
# 영업일 (B)
date_range = pd.date_range(
    start='20250228'
    , periods=5
    , freq='W'
)
print(date_range)

DatetimeIndex(['2025-03-02', '2025-03-09', '2025-03-16', '2025-03-23',
               '2025-03-30'],
              dtype='datetime64[ns]', freq='W-SUN')


In [ ]:
# 날짜 인덱스 생성
import numpy as np
import pandas as pd
# datetime 모듈에서 datetime 클래스를 갖고와라 = 결과적으로 클래스 import 한것
from datetime import datetime

now = datetime.now()
print(now)

date_idx = pd.date_range(
    start=now
    ,periods=5
)
print(date_idx)


2025-02-28 14:12:28.844577
DatetimeIndex(['2025-02-28 14:12:28.844577', '2025-03-01 14:12:28.844577',
               '2025-03-02 14:12:28.844577', '2025-03-03 14:12:28.844577',
               '2025-03-04 14:12:28.844577'],
              dtype='datetime64[ns]', freq='D')


---
#### 인덱싱, 슬라이싱(인덱싱), 팬시색인(인덱싱), 불린인덱싱
---

- 행이나 컬럼 추출 목적
- 1. 행 기준 추출 : loc[], iloc[]
- 2. 컬럼 기준 추출 : ['컬럼명'], [['컬럼명','컬럼명']]
- 3. 인덱싱 : 정수 인덱스, 네임드 인덱스 사용 방식이 있다


In [43]:
# 인덱싱, 슬라이싱
# 정수인덱스, 네임드인덱스
data = {
      'Name' : ['홍길동','고길동','마이꼴','둘리','희동']
    , 'Age' : [20,30,20,1000,2]
    , 'Addr' : ['울릉도','서울','서울','별','서울']
}
df = pd.DataFrame(data)
df


Name   Age Addr
0  홍길동    20  울릉도
1  고길동    30   서울
2  마이꼴    20   서울
3   둘리  1000    별
4   희동     2   서울

In [44]:
print(df['Name'])
print(df['Age'])
print(df['Addr'])

0    홍길동
1    고길동
2    마이꼴
3     둘리
4     희동
Name: Name, dtype: object
0      20
1      30
2      20
3    1000
4       2
Name: Age, dtype: int64
0    울릉도
1     서울
2     서울
3      별
4     서울
Name: Addr, dtype: object


In [45]:
# 인덱스 0번으로 홍길동, 20, 울릉도 연결 // 원래 데이터가 이렇게 다 떨어져있는데 그걸 묶어주는게 index
# 즉, 인덱스는 key처럼 사용된다. = 3개 컬럼을 이어주는 key

In [46]:
print(df.loc[0,:])
print(df.iloc[0,:])
print(df)

Name    홍길동
Age      20
Addr    울릉도
Name: 0, dtype: object
Name    홍길동
Age      20
Addr    울릉도
Name: 0, dtype: object
  Name   Age Addr
0  홍길동    20  울릉도
1  고길동    30   서울
2  마이꼴    20   서울
3   둘리  1000    별
4   희동     2   서울


In [47]:
# print(df.loc[0,:])
# print(df.iloc[0,:])
# 이렇게 둘다 접근이 가능하다. 왜? 인덱스가 숨겨져 있어서

In [48]:
print(df.index)

RangeIndex(start=0, stop=5, step=1)


In [49]:
df

Name   Age Addr
0  홍길동    20  울릉도
1  고길동    30   서울
2  마이꼴    20   서울
3   둘리  1000    별
4   희동     2   서울

In [50]:
# 특정 컬럼을 인덱스 영역으로 보내는 작업
# set_index(지정한 컬럼)
df = df.set_index('Name')
df
# name이 index로 갔고 이제 key역할을 한다.

Age Addr
Name           
홍길동     20  울릉도
고길동     30   서울
마이꼴     20   서울
둘리    1000    별
희동       2   서울

In [187]:
# 홍길동의 데이터 추출(행추출)
df.loc['홍길동']

Age      20
Addr    울릉도
Name: 홍길동, dtype: object

In [189]:
# 팬시 색인 : 홍길동 마이꼴 추출
df.loc[['홍길동','마이꼴']]

Age Addr
Name          
홍길동    20  울릉도
마이꼴    20   서울

In [190]:
# 불린 인덱싱
# 나이가 20 이상인 데이터 추출
df['Age'] > 20

Name
홍길동    False
고길동     True
마이꼴    False
둘리      True
희동     False
Name: Age, dtype: bool

In [191]:
df[df['Age']>20]

Age Addr
Name           
고길동     30   서울
둘리    1000    별

In [192]:
# 슬라이싱 : 고길동부터 둘리 행단위 추출
df.loc['고길동':'둘리']

Age Addr
Name           
고길동     30   서울
마이꼴     20   서울
둘리    1000    별

In [193]:
df

Age Addr
Name           
홍길동     20  울릉도
고길동     30   서울
마이꼴     20   서울
둘리    1000    별
희동       2   서울

In [201]:
# 구분 컬럼 추가
df['gubun'] = ['가족','친구','회사','기타','가족']
df

Age Addr gubun
Name                 
홍길동     20  울릉도    가족
고길동     30   서울    친구
마이꼴     20   서울    회사
둘리    1000    별    기타
희동       2   서울    가족

In [202]:
df

Age Addr gubun
Name                 
홍길동     20  울릉도    가족
고길동     30   서울    친구
마이꼴     20   서울    회사
둘리    1000    별    기타
희동       2   서울    가족

In [204]:
# 가족, 친구 검색
# 불린 인덱스
df['gubun'].isin(['가족','친구']) # boolean return

Name
홍길동     True
고길동     True
마이꼴    False
둘리     False
희동      True
Name: gubun, dtype: bool

In [205]:
df[df['gubun'].isin(['가족','친구'])]

Age Addr gubun
Name                
홍길동    20  울릉도    가족
고길동    30   서울    친구
희동      2   서울    가족